### PARA ENVIAR UN SMS A UN USUARIO

POST http://localhost:3000/api/send-sms
Content-Type: application/json

{
    "to": "+593980834740"
}

### PARA CREAR NIVEL DE AGUA EN UNA CIUDAD O REGISTRAR UN NUEVO NIVEL DE AGUA

POST http://localhost:3000/api/nivel-agua/nuevo
Content-Type: application/json

{
    "value": 6
}

### PARA PREDECIR EL NIVEL DE AGUA EN UN DÍA ESPECÍFICO

POST http://localhost:3000/api/nivel-agua/predict
Content-Type: application/json

{
    "date": "2021-10-01"
}


